name: Python Selenium Tests

on:
    pull_request:
      branches:
        - master

jobs:
  selenium-tests:
    runs-on: ubuntu-latest
    services:
      selenium:
        image: selenium/standalone-chrome
        options: >-
          --shm-size 2g
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python 3.x
        uses: actions/setup-python@v3
        with:
          python-version: 3.x

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          sudo apt-get install -y google-chrome-stable
          pip install -r requirements.txt

      - name: Run Selenium tests
        run: |
          python -m pytest --maxfail=1 --disable-warnings
